name: CICD
on: [push]
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]    
    steps:

      - name: Checkout test
        uses: actions/checkout@master
        with:
                #branches:
                #develop
          path: test
